linters:
  fast: true
  enable:
    - gofmt
    - bodyclose
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - maligned
    - depguard
    - misspell
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic