version: 2

jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run:
          name: go test
          command: make test
      - run:
          name: go build
          command: make build
      - persist_to_workspace:
          root: /root/project/
          paths:
            - bin/

  release:
    docker:
      - image: rdaniels6813/semantic-release-alpine:latest
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root/project
      - run:
          name: Release
          command: make release

workflows:
  version: 2
  build:
    jobs:
      - 'build'
      - release:
          requires:
            - 'build'
          filters:
            branches:
              only: master
