name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version-file: '../../go.mod'
          check-latest: true
          cache: true
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Test
        run: task test
      - name: Build
        run: task build
      - name: Setup Node - Semantic Release
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install - Semantic Release
        run: |
          npm i -g semantic-release@20 \
            @semantic-release/commit-analyzer@9 \
            @semantic-release/release-notes-generator@10 \
            @semantic-release/github@8 \
            @semantic-release/exec@6 \
            @semantic-release/changelog@6 \
            @semantic-release/git@10
      - name: Run - Semantic Release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
